---

- name: 'INSTALL | YUM | Install xvfb packages'
  become: True
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  notify: 'HANDLER | Restart xvfb'
  with_items: "{{ xvfb_packages }}"
