---

- name: 'INSTALL | APT | Install xvfb packages'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ xvfb_repository_cache_valid_time }}"
  notify: 'HANDLER | Restart xvfb'
  with_items: "{{ xvfb_packages }}"
