---

# Handlers main file for xvfb role

- name: 'HANDLER | Restart xvfb'
  become: True
  service:
    name: "{{ xvfb_service_name }}"
    state: 'restarted'
  tags:
    - 'role::xvfb'
    - 'role::xvfb::install'
