---

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "xvfb-docker-centos7"
    command: "/sbin/init"
    groups:
      - 'centos'
    image: 'jrei/systemd-centos:7'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "xvfb-docker-centos8"
    command: "/sbin/init"
    groups:
      - 'centos'
    image: 'jrei/systemd-centos:8'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "xvfb-docker-debian9"
    command: "/sbin/init"
    groups:
      - 'debian'
    image: 'jrei/systemd-debian:9'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "xvfb-docker-debian10"
    command: "/sbin/init"
    groups:
      - 'debian'
    image: 'jrei/systemd-debian:10'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "xvfb-docker-ubuntu18"
    command: "/sbin/init"
    groups:
      - 'ubuntu'
    image: 'jrei/systemd-ubuntu:18.04'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "xvfb-docker-ubuntu20"
    command: "/sbin/init"
    groups:
      - 'ubuntu'
    image: 'jrei/systemd-ubuntu:20.04'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
provisioner:
  name: 'ansible'
  inventory:
    group_vars:
      all: {}
    host_vars: {}
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  additional_files_or_dirs:
    - '../../tests'
  options:
    sudo: True
